# Generated by Django 2.2.7 on 2019-11-24 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191124_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 7, 45, 51, 513279, tzinfo=utc)),
        ),
    ]
