# Generated by Django 2.2.7 on 2019-11-24 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191124_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 9, 0, 7, 392509, tzinfo=utc)),
        ),
    ]
