# Generated by Django 2.2.2 on 2019-11-24 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191124_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 15, 54, 22, 295955, tzinfo=utc)),
        ),
    ]
