# Generated by Django 2.2.2 on 2019-11-25 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191124_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 6, 8, 7, 352690, tzinfo=utc)),
        ),
    ]
