# Generated by Django 2.2.2 on 2019-11-25 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191125_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 7, 49, 21, 202624, tzinfo=utc)),
        ),
    ]
