# Generated by Django 2.1.14 on 2019-11-26 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191125_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 14, 37, 20, 684748, tzinfo=utc)),
        ),
    ]
